### ISSUE TITLE
Sistema base di autorizzazioni

### ISSUE THREAD

**Issue by N-essuno** [tsi-unito/UnitoBOT#10]
Assumendo che nel DB ci sia una relazione `(id_utente, ruolo)`, dove `ruolo `è una stringa. Creare una funzione che data una coppia `(id_utente, ruolo_atteso)` restituisce `true` se l'utente ha `ruolo_atteso`, `false` altrimenti.
Questa funzione sarà usata all'interno di altre funzioni per fare un check delle autorizzazioni prima di eseguirle.

**Comment by stefa168** [comment]
Come abbiamo discusso insieme, per verificare l'autorizzazione faremo query da DB.

C'è la possibilità di tenere in memoria gli utenti che hanno uno specifico ruolo, tuttavia per evitare problemi di consistenza dei dati direi che per ora è semplice gestire tutto da DB.

La funzione accetterà come parametro per `ruolo` un tipo `str | list[str]`.
